name = "do-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
JWT_SECRET = "your-jwt-secret-for-local-development-only"

kv_namespaces = [
  { binding = "EXAMPLE_KV", id = "a-shared-id" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "BlogDO" ]

[[durable_objects.bindings]]
name = "BLOG_DO"
class_name = "BlogDO"